services:
  mongo:
    image: bitnami/mongodb:7.0.12
    environment:
      TZ: Asia/Shanghai
      MONGODB_DATABASE: local_db
      MONGODB_USERNAME: mongo
      MONGODB_PASSWORD: mongo
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: root
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: rsk123456
      MONGODB_EXTRA_FLAGS: >
        --bind_ip_all
    ports:
      - "27017:27017"
  redis:
    image: redis/redis-stack:7.2.0-v10
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      TZ: Asia/Shanghai
      REDIS_ARGS: >
        --requirepass redispw
  redis-streams:
    image: redis/redis-stack:7.2.0-v10
    ports:
      - "6380:6380"
      - "8002:8001"
    environment:
      TZ: Asia/Shanghai

  postgres:
    build:
      context: .
      dockerfile: fit-common/postgres-wal2json/Dockerfile
    ports:
      - "5432:5432"
    #    volumes:
    #      - ./postgres-persistence:/bitnami/postgresql
    environment:
      TZ: Asia/Shanghai
      PGDATA: /bitnami/postgresql/data
      USE_DB_ID: true
      USE_JSON_PAYLOAD_AND_HEADERS: true
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: fit
      POSTGRESQL_EXTRA_FLAGS: >
        -c wal_level=logical 
        -c timezone=Asia/Shanghai 
        -c log_timezone=Asia/Shanghai