spring:
  application:
    name: fit-application
  output:
    ansi:
      enabled: always
  threads:
    virtual:
      enabled: true
  main:
    keep-alive: true
  security:
    oauth2:
      authorizationserver:
        token:
          customizer:
            ahead-auto-refresh: 55m
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
      authentication-database: admin
      database: local_db
  cache:
    type: redis
    redis:
      key-prefix: "Cache::"
      time-to-live: 7d
  redis:
    redisson:
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          subscriptionsPerConnection: 5
          clientName: null
          address: redis://127.0.0.1:6379
          password: redispw
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 1024
          connectionMinimumIdleSize: 1024
          connectionPoolSize: 1024
          database: 0
          dnsMonitoringInterval: 5000
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.codec.Kryo5Codec> {}
        transportMode: "NIO"
  mail:
    host: smtp.qq.com
    port: 465
    username: masked
    password: masked
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
  messages:
    ali-yun:
      sms-sign-name: masked
      sms-template-code: masked
      access-key: masked
      secret: masked

eventuate:
  redis:
    partitions: 1

springdoc:
  swagger-ui:
    persist-authorization: true
    default-models-expand-depth: -1
    syntax-highlight:
      activated: true

logging:
  level:
    #    io.eventuate: warn
    #    io.eventuate.messaging.redis.spring.producer.EventuateRedisProducer: info
    org.springframework.data.mongodb.core.MongoTemplate: debug
    io.netty.resolver.dns.DnsServerAddressStreamProviders: error

