spring:
  application:
    name: fit-application
  output:
    ansi:
      enabled: always
  threads:
    virtual:
      enabled: true
  main:
    keep-alive: true
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
      authentication-database: admin
      database: local_db
  redis:
    redisson:
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          subscriptionsPerConnection: 5
          clientName: null
          address: redis://127.0.0.1:6379
          password: redispw
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 1024
          connectionMinimumIdleSize: 1024
          connectionPoolSize: 1024
          database: 0
          dnsMonitoringInterval: 5000
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.codec.Kryo5Codec> {}
        transportMode: "NIO"

eventuate:
  redis:
    partitions: 1
logging:
  level:
#    io.eventuate: warn
#    io.eventuate.messaging.redis.spring.producer.EventuateRedisProducer: info
    org.springframework.data.mongodb.core.MongoTemplate: debug
    io.netty.resolver.dns.DnsServerAddressStreamProviders: error
    org.springframework.data.repository.config.RepositoryConfigurationExtensionSupport: warn
